// Fecha de viaje: 2 noviembre 2026
// Hoy: 28 mayo 2026 → días hasta el viaje: ~157 días

export const CURRENCIES = { KRW: 'KRW', JPY: 'JPY', USD: 'USD' }

export const URGENCY = {
  NOW: 'now',       // comprar ya (meses antes)
  SOON: 'soon',     // semanas antes
  LATER: 'later',   // en destino o días antes
}

// buyBy: fecha límite sugerida para comprar (YYYY-MM-DD)
// useDate: fecha en que se usa (del itinerario)
// price: precio estimado en moneda local
// currency: KRW | JPY | USD
export const ITEMS_DEFAULT = [
  // ─── VUELOS ───────────────────────────────────────────────
  {
    id: 'flight-pus-kix',
    category: 'Vuelos',
    name: 'Vuelo Busan (PUS) → Osaka (KIX)',
    description: 'LCC recomendada: Jeju Air, Air Busan o Peach. El más temprano posible.',
    urgency: URGENCY.NOW,
    buyBy: '2026-07-01',
    useDate: '2026-11-09',
    price: 120000,
    currency: CURRENCIES.KRW,
    link: 'https://www.skyscanner.com',
  },

  // ─── TRENES COREA ─────────────────────────────────────────
  {
    id: 'ktx-seoul-jeonju',
    category: 'Trenes Corea',
    name: 'KTX Seúl → Jeonju (ida y vuelta)',
    description: 'Desde Yongsan, ~1h50 cada tramo. Reservar asiento.',
    urgency: URGENCY.SOON,
    buyBy: '2026-10-10',
    useDate: '2026-11-05',
    price: 35800,
    currency: CURRENCIES.KRW,
    link: 'https://www.letskorail.com',
  },
  {
    id: 'ktx-seoul-gyeongju',
    category: 'Trenes Corea',
    name: 'KTX Seúl → Gyeongju (Singyeongju)',
    description: 'Salida ~6:30h. Reservar con anticipación.',
    urgency: URGENCY.SOON,
    buyBy: '2026-10-10',
    useDate: '2026-11-07',
    price: 42600,
    currency: CURRENCIES.KRW,
    link: 'https://www.letskorail.com',
  },
  {
    id: 'bus-bulguksa-busan',
    category: 'Trenes Corea',
    name: 'Bus Bulguksa → Busan',
    description: 'Bus directo desde el templo. Sin reserva previa.',
    urgency: URGENCY.LATER,
    buyBy: '2026-11-07',
    useDate: '2026-11-07',
    price: 4000,
    currency: CURRENCIES.KRW,
    link: null,
  },

  // ─── TRENES JAPÓN ─────────────────────────────────────────
  {
    id: 'jr-pass',
    category: 'Trenes Japón',
    name: 'JR Pass (14 días)',
    description: 'Cubre Shinkansen Kyoto→Tokyo + trenes JR. Comprar online antes de viajar y activar al llegar a Japón.',
    urgency: URGENCY.NOW,
    buyBy: '2026-09-01',
    useDate: '2026-11-09',
    price: 70000,
    currency: CURRENCIES.JPY,
    link: 'https://japanrailpass.net',
  },
  {
    id: 'shinkansen-kyoto-tokyo',
    category: 'Trenes Japón',
    name: 'Shinkansen Kyoto → Tokyo (Nozomi)',
    description: 'Reservar asiento. Incluido en JR Pass — solo reserva de asiento (~¥0 adicional con pass).',
    urgency: URGENCY.SOON,
    buyBy: '2026-10-01',
    useDate: '2026-11-14',
    price: 0,
    currency: CURRENCIES.JPY,
    link: 'https://japanrailpass.net',
  },
  {
    id: 'train-tokyo-kamakura',
    category: 'Trenes Japón',
    name: 'Tren Tokyo → Kamakura (JR Yokosuka Line)',
    description: '~1h desde Tokyo. Incluido en JR Pass o comprar en máquina.',
    urgency: URGENCY.LATER,
    buyBy: '2026-11-18',
    useDate: '2026-11-18',
    price: 940,
    currency: CURRENCIES.JPY,
    link: null,
  },
  {
    id: 'train-osaka-nara',
    category: 'Trenes Japón',
    name: 'Tren Osaka → Nara (Kintetsu)',
    description: '~45 min. Sin reserva previa, comprar en máquina.',
    urgency: URGENCY.LATER,
    buyBy: '2026-11-12',
    useDate: '2026-11-12',
    price: 560,
    currency: CURRENCIES.JPY,
    link: null,
  },

  // ─── TARJETAS DE TRANSPORTE ───────────────────────────────
  {
    id: 't-money',
    category: 'Tarjetas de transporte',
    name: 'T-Money (Corea)',
    description: 'Metro, bus y AREX en Seúl y Busan. Comprar en Incheon al llegar.',
    urgency: URGENCY.LATER,
    buyBy: '2026-11-02',
    useDate: '2026-11-02',
    price: 4000,
    currency: CURRENCIES.KRW,
    link: null,
  },
  {
    id: 'ic-card-japan',
    category: 'Tarjetas de transporte',
    name: 'IC Card Japón (Suica / ICOCA)',
    description: 'Metro, buses y tiendas en Osaka, Kyoto y Tokyo. Comprar al llegar a KIX.',
    urgency: URGENCY.LATER,
    buyBy: '2026-11-09',
    useDate: '2026-11-09',
    price: 2000,
    currency: CURRENCIES.JPY,
    link: null,
  },

  // ─── ENTRADAS ─────────────────────────────────────────────
  {
    id: 'usj-ticket',
    category: 'Entradas',
    name: 'Universal Studios Japan — entrada + Express Pass',
    description: 'Se agotan semanas antes. Reservar turno Super Nintendo World desde la app oficial por separado.',
    urgency: URGENCY.NOW,
    buyBy: '2026-09-15',
    useDate: '2026-11-11',
    price: 23400,
    currency: CURRENCIES.JPY,
    link: 'https://www.usj.co.jp/web/en/us',
  },
  {
    id: 'shibuya-sky',
    category: 'Entradas',
    name: 'Shibuya Sky (observatorio, atardecer)',
    description: 'La mejor vista de Tokyo. Se agota con semanas de anticipación.',
    urgency: URGENCY.NOW,
    buyBy: '2026-10-20',
    useDate: '2026-11-19',
    price: 2200,
    currency: CURRENCIES.JPY,
    link: 'https://shibuya-scramble-square.com/sky/',
  },
  {
    id: 'osaka-castle',
    category: 'Entradas',
    name: 'Castillo de Osaka',
    description: 'Pagar en taquilla. Ir temprano para evitar colas.',
    urgency: URGENCY.LATER,
    buyBy: '2026-11-10',
    useDate: '2026-11-10',
    price: 600,
    currency: CURRENCIES.JPY,
    link: null,
  },
  {
    id: 'kodaiji-lights',
    category: 'Entradas',
    name: 'Templo Kōdai-ji — luces nocturnas',
    description: 'No es todos los días. Confirmar disponibilidad antes del viaje.',
    urgency: URGENCY.SOON,
    buyBy: '2026-11-01',
    useDate: '2026-11-13',
    price: 600,
    currency: CURRENCIES.JPY,
    link: 'https://www.kodaiji.com',
  },
  {
    id: 'tenryuji',
    category: 'Entradas',
    name: 'Tenryu-ji (jardín UNESCO, Arashiyama)',
    description: 'Sin reserva, pagar en taquilla.',
    urgency: URGENCY.LATER,
    buyBy: '2026-11-14',
    useDate: '2026-11-14',
    price: 500,
    currency: CURRENCIES.JPY,
    link: null,
  },
  {
    id: 'kinkakuji',
    category: 'Entradas',
    name: 'Kinkaku-ji (Pabellón Dorado)',
    description: 'Sin reserva, pagar en taquilla.',
    urgency: URGENCY.LATER,
    buyBy: '2026-11-14',
    useDate: '2026-11-14',
    price: 500,
    currency: CURRENCIES.JPY,
    link: null,
  },
  {
    id: 'nijo-castle',
    category: 'Entradas',
    name: 'Castillo Nijō',
    description: 'Sin reserva, pagar en taquilla.',
    urgency: URGENCY.LATER,
    buyBy: '2026-11-14',
    useDate: '2026-11-14',
    price: 1000,
    currency: CURRENCIES.JPY,
    link: null,
  },
  {
    id: 'blueline-busan',
    category: 'Entradas',
    name: 'Blueline (tren costero Haeundae–Mipo)',
    description: 'Tren turístico sobre el acantilado. Tickets en boletería, puede haber espera.',
    urgency: URGENCY.LATER,
    buyBy: '2026-11-08',
    useDate: '2026-11-08',
    price: 12000,
    currency: CURRENCIES.KRW,
    link: null,
  },
  {
    id: 'umeda-sky',
    category: 'Entradas',
    name: 'Umeda Sky Building (observatorio)',
    description: 'Sin reserva obligatoria, ir temprano.',
    urgency: URGENCY.LATER,
    buyBy: '2026-11-09',
    useDate: '2026-11-09',
    price: 1500,
    currency: CURRENCIES.JPY,
    link: null,
  },
]

export const CATEGORIES = [...new Set(ITEMS_DEFAULT.map(i => i.category))]
